---
platform: linux
inputs:
- name: git-repo
outputs:
- name: distribution-repository
caches:
- path: maven
- path: gradle
run:
  path: bash
  args:
    - -exc
    - |
      source /docker-lib.sh
      start_docker
      ${PWD}/git-repo/ci/scripts/build-project.sh
params:
  ARTIFACTORY_USERNAME: ((artifactory-username))
  ARTIFACTORY_PASSWORD: ((artifactory-password))
  BUILD_NUMBER: "${BUILD_PIPELINE_NAME}-${BUILD_JOB_NAME}-${BUILD_NAME}"
