---
platform: linux
inputs:
- name: git-repo
caches:
- path: maven
- path: gradle
run:
  path: bash
  args:
    - -exc
    - |
      source /docker-lib.sh
      start_docker
      ${PWD}/git-repo/ci/scripts/build-project.sh
params:
  FOO_BAR: foobar
      