email-server: "smtp.svc.pivotal.io"
email-from: "ci@spring.io"
email-to: ["jvalkealahti@pivotal.io"]
github-repo: "https://github.com/jvalkeal/sat-wip.git"
github-repo-name: "jvalkeal/sat-wip"
docker-hub-organization: "springci"
artifactory-server: "https://repo.spring.io/"
branch: "master"
build-name: "sat-wip"
