resource_types:
- name: artifactory-resource
  type: docker-image
  source:
    repository: springio/artifactory-resource
    tag: 0.0.3
resources:
- name: git-repo
  type: git
  source:
    uri: ((github-repo))
    branch: ((branch))
    ignore_paths: ["ci/images/*"]
- name: ci-images-git-repo
  type: git
  source:
    uri: ((github-repo))
    branch: ((branch))
    paths: ["ci/images/*"]
- name: artifactory-repo
  type: artifactory-resource
  source:
    uri: ((artifactory-server))
    username: ((artifactory-username))
    password: ((artifactory-password))
    build_name: ((build-name))    
- name: spring-cloud-skipper-ci-image
  type: docker-image
  source:
    repository: springsource-docker-private-local.jfrog.io/spring-cloud-skipper-ci-image
    username: ((artifactory-username))
    password: ((artifactory-password))
    tag: ((branch))
jobs:
- name: spring-cloud-skipper-ci-images
  plan:
  - get: ci-images-git-repo
    trigger: true
  - put: spring-cloud-skipper-ci-image
    params:
      build: ci-images-git-repo/ci/images/spring-cloud-skipper-ci-image
- name: build
  serial: true
  public: false
  plan:
  - get: spring-cloud-skipper-ci-image
  - get: git-repo
    trigger: true
  - do:
    - task: build-project
      privileged: true
      timeout: 30m
      image: spring-cloud-skipper-ci-image
      file: git-repo/ci/tasks/build-project.yml
- name: build-skipper-server-with-drivers
  serial: true
  public: false
  plan:
  - get: spring-cloud-skipper-ci-image
  - get: git-repo
    trigger: false
  - do:
    - task: build-skipper-server-with-drivers
      privileged: true
      timeout: 30m
      image: spring-cloud-skipper-ci-image
      file: git-repo/ci/tasks/build-skipper-server-with-drivers.yml
  - put: artifactory-repo
    params: &artifactory-params
      repo: libs-snapshot-local
      folder: distribution-repository
      build_uri: "https://ci.spring.io/teams/${BUILD_TEAM_NAME}/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}"
      build_number: "${BUILD_PIPELINE_NAME}-${BUILD_JOB_NAME}-${BUILD_NAME}"
      disable_checksum_uploads: true
groups:
- name: "Build"
  jobs: ["build", "build-skipper-server-with-drivers"]
- name: "CI Images"
  jobs: ["spring-cloud-skipper-ci-images"]
