resources:
- name: git-repo
  type: git
  source:
    uri: ((github-repo))
    username: ((github-username))
    password: ((github-password))
    branch: ((branch))
    ignore_paths: ["ci/images/*"]
- name: spring-boot-ci-image
  type: docker-image
  source:
    repository: ((docker-hub-organization))/spring-boot-ci-image
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    tag: ((branch))
jobs:
- name: build
  serial: true
  public: true
  plan:
  - get: git-repo
    trigger: true
  - do:
    - task: build-project
      privileged: true
      timeout: 30m
      image: spring-boot-ci-image
      file: git-repo/ci/tasks/build-project.yml
    